name: eshoponweb-ci

on:
  push:
    branches: [ feature/* ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore eShopOnWeb.sln

    - name: Build
      run: dotnet build eShopOnWeb.sln --no-restore --configuration Release

    - name: Run tests
      run: dotnet test eShopOnWeb.sln --no-build --configuration Release --verbosity normal